LPD 27101 20240607
liferay-devtools/liferay-portal pull request #115
Opened 2024-06-26 00:08 UTC by kyle-miho

- **LPD-27101 Add unit tests for upgrading service implementations component annotation**
- **LPD-27101 Automate upgrading to the component annotation for service implementation files that now use DS**
- **LPD-27101 Autogenerated**
- **LPD-27101 source-formatter: moves duplicate logic into abstract base class**
- **LPD-27101 source-formatter: adds missing parenthesis**
- **LPD-27101 Use more accurate name**
- **LPD-27101 Fixed formatting issues**
- **LPD-27101 Avoid using StringUtil.merge to merge lines since it trims away tabs**
- **LPD-27101 Set initial capacity for StringBundler**
- **LPD-27101 Fix copyright**
- **LPD-27101 SF**
- **LPD-27101 Generated**
- **LPD-27101 Simplify**
- **LPD-27101 Allow absolute path to be used as a parameter**
- **LPD-27101 Grab context name from portletShortName from service.xml and leave the old method as a fallback**
- **LPD-27101 Add service.xml to the unit test dependencies to simulate a real service module**

2024-06-26 00:08 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-06-26 00:09 UTC, kyle-miho commented
ci:test:sf

2024-06-26 00:09 UTC, kyle-miho commented
ci:test:hotel

2024-06-26 00:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>hotel</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10130/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10130/jenkins-report.html">here</a>.</b></p>

2024-06-26 00:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3576/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3576/jenkins-report.html">here</a>.</b></p>

2024-06-26 01:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:hotel - 2 out of 2 jobs passed in 50 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4053233efc7665eaa07fc901fcf1c39d89e2721e">4053233efc7665eaa07fc901fcf1c39d89e2721e</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/abc4222371a1a253ae05ecb3e6083858ac965415">abc4222371a1a253ae05ecb3e6083858ac965415</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/25652125">EE Development Acceptance (master) - 623 - 2024-06-25[04:39:29]</a></p><details><summary><strong>ci:test:hotel - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/10130/">test-portal-acceptance-pullrequest(master)</a></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/403906/">modules-unit-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10130/jenkins-report.html">here</a>.</h5></details></html>

2024-06-26 01:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 1 hour 49 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4053233efc7665eaa07fc901fcf1c39d89e2721e">4053233efc7665eaa07fc901fcf1c39d89e2721e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/kyle-miho/liferay-portal/tree/LPD-27101_20240607">LPD-27101_20240607</a><br/>Branch GIT ID: <a href="https://github.com/kyle-miho/liferay-portal/commit/d80199c766e71a94337a5ddc7948a1af91cdf472">d80199c766e71a94337a5ddc7948a1af91cdf472</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3576/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3576/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] SLF4J: Class path contains multiple SLF4J bindings.
     [java] SLF4J: Found binding in [file:/opt/dev/projects/github/liferay-portal/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
     [java] SLF4J: Actual binding is of type [com.liferay.util.slf4j.LiferayLoggerFactory]
     [java] java.lang.Exception: Found 4 formatting issues:
     [java] 1: There should be an empty line before line '128', as we finished referencing variable 'autoSiteNavigationMenu', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/apps/site-navigation/site-navigation-menu-item-layout-test/src/testIntegration/java/com/liferay/site/navigation/menu/item/layout/internal/type/test/LayoutSiteNavigationMenuItemTypeTest.java 128 (Checkstyle:MissingEmptyLineCheck)
     [java] 2: Test dependencies file '/opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/Technology.xml' is only referenced by one module, move it to module dependencies directory: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/misc/rss/RSS.testcase (SourceCheck:PoshiDependenciesFileLocationCheck)
     [java] 3: ./modules/apps/layout/layout-seo-test/src/testIntegration/java/com/liferay/layout/seo/test/LayoutSEOLinkManagerPageTitleTest.java expected:&lt;..._group.getGroupId(),[ _PID,
     [java]             HashMapDictionaryBuilder.&lt;String, Object&gt;put(
     [java]               "includeInstanceName", true
     [java]             ).put(
     [java]               "includeSiteName", true
     [java]             ).build())) \{
     [java] 
     [java]       String companyName = RandomTestUtil.randomString();
     [java] 
     [java]       Assert.assertEquals(
     [java]         StringBundler.concat(
     [java]           _layout.getTitle(), " - ", _group.getName(), " - ",
     [java]           companyName),
     [java]         _layoutSEOLinkManager.getFullPageTitle(
     [java]           _layout, null, null, null, null, companyName,
     [java]           LocaleUtil.getDefault()));
     [java] </pre></details></html>

2024-06-26 02:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3576/">test-portal-source-format#3576</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3576/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/115">liferay-devtools#115</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/26207183">[master] ci:test:sf - kyle-miho &gt; liferay-devtools - PR#115 - 2024-06-25[17:09:36]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>26207183<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/14119/">publish-testray-report#14119</a><br/></div></div>

2024-06-28 18:25 UTC, drewbrokke requested changes
Just the one comment to check @kyle-miho. Otherwise this looks good. Thanks!

2024-06-28 18:25 UTC, drewbrokke commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaServiceImplCheck.java
> +	}
@kyle-miho there may be a utility in SourceFormatter that accomplishes this already.

@ling-alan-huang any leads?

2024-07-01 07:04 UTC, ling-alan-huang commented
see https://github.com/liferay-devtools/liferay-portal/pull/120

2024-07-01 07:04 UTC, closed without merging