master lpd 29866
liferay-devtools/liferay-portal pull request #189
Opened 2024-08-29 15:14 UTC by kyle-miho

- **LPD-29866 Add unit testing for upgrading StorageEngine service in ftl files**
- **LPD-29866 Add upgrade for StorageEngine service in ftl files**
- **LPD-29866 Allow regex replacements to be used outside of java files as well**
- **LPD-29866 Split UpgradeCatchAllCheck tests into their respective extensions to reduce individual runtime**

2024-08-29 15:14 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-08-29 15:28 UTC, kyle-miho commented
ci:test:sf

2024-08-29 15:28 UTC, kyle-miho commented
ci:test:hotel

2024-08-29 15:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/3462/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3462/jenkins-report.html">here</a>.</b></p>

2024-08-29 15:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 24 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f596aec2903cb48fb61f42252ecfaf38304011b">7f596aec2903cb48fb61f42252ecfaf38304011b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/kyle-miho/liferay-portal/tree/master-lpd-29866">master-lpd-29866</a><br/>Branch GIT ID: <a href="https://github.com/kyle-miho/liferay-portal/commit/891a7b54e93ae1d1bedce4809916f6ea91008f84">891a7b54e93ae1d1bedce4809916f6ea91008f84</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3462/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3462/jenkins-report.html">here</a>.</h5></details></html>

2024-08-29 15:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3462/">test-portal-source-format#3462</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3462/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/189">liferay-devtools#189</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/74718311">[master] ci:test:sf - kyle-miho &gt; liferay-devtools - PR#189 - 2024-08-29[08:28:36]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>74718311<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/14321/">publish-testray-report#14321</a><br/></div></div>

2024-08-29 17:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:hotel - 2 out of 2 jobs passed in 1 hour</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f596aec2903cb48fb61f42252ecfaf38304011b">7f596aec2903cb48fb61f42252ecfaf38304011b</a></p><details><summary><strong>ci:test:hotel - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13834/">test-portal-acceptance-pullrequest(master)</a></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/370623/">modules-unit-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13834/jenkins-report.html">here</a>.</h5></details></html>

2024-08-29 17:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/13834/">test-portal-acceptance-pullrequest(master)#13834</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13834/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>hotel<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/189">liferay-devtools#189</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/74744335">[master] ci:test:hotel - kyle-miho &gt; liferay-devtools - PR#189 - 2024-08-29[08:28:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>74744335<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/32281/">publish-testray-report#32281</a><br/></div></div>

2024-09-02 16:16 UTC, nicolas-sss requested changes

2024-09-02 16:16 UTC, nicolas-sss commented on modules/util/source-formatter/src/main/resources/dependencies/replacements.json
> +		]
Hi @kyle-miho, can the service locator call be split into two lines?
Generally for good practice, we add optional \n in ".", "(", etc. To catch those cases.

2024-09-02 16:16 UTC, nicolas-sss commented on modules/util/source-formatter/src/main/resources/dependencies/replacements.json
> +		]
Or does the default logic for the regex in the code already deal with that?

2024-09-06 19:03 UTC, kyle-miho commented
ci:test:sf

2024-09-06 19:03 UTC, kyle-miho commented
ci:test:hotel

2024-09-06 19:04 UTC, kyle-miho commented
@nicolas-sss I accounted for new line SF changes now

2024-09-06 19:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>hotel</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12490/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12490/jenkins-report.html">here</a>.</b></p>

2024-09-06 19:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/8197/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/8197/jenkins-report.html">here</a>.</b></p>

2024-09-06 19:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 27 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2b61f9669df9f4e824d01edf90bf148c0bd825e">e2b61f9669df9f4e824d01edf90bf148c0bd825e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/kyle-miho/liferay-portal/tree/master-lpd-29866">master-lpd-29866</a><br/>Branch GIT ID: <a href="https://github.com/kyle-miho/liferay-portal/commit/6d769b29c42d646acdaa9ffa94993384f22f2e40">6d769b29c42d646acdaa9ffa94993384f22f2e40</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/8197/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/8197/jenkins-report.html">here</a>.</h5></details></html>

2024-09-06 19:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:hotel - 2 out of 2 jobs passed in 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2b61f9669df9f4e824d01edf90bf148c0bd825e">e2b61f9669df9f4e824d01edf90bf148c0bd825e</a></p><details><summary><strong>ci:test:hotel - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12490/">test-portal-acceptance-pullrequest(master)</a></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1083135/">modules-unit-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12490/jenkins-report.html">here</a>.</h5></details></html>

2024-09-09 17:06 UTC, nicolas-sss approved these changes

2024-09-12 14:59 UTC, closed without merging