Nicolas - SF Automation - Master LPD-35875
liferay-devtools/liferay-portal pull request #208
Opened 2024-09-09 20:52 UTC by MicaelleSilvaa

Ticket: https://liferay.atlassian.net/browse/LPD-35875

2024-09-09 20:52 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-09-09 20:53 UTC, MicaelleSilvaa commented
ci:test:sf

2024-09-09 20:53 UTC, MicaelleSilvaa commented
ci:test:hotel

2024-09-09 20:56 UTC, MicaelleSilvaa commented
ci:test:sf

2024-09-09 20:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/4082/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/4082/jenkins-report.html">here</a>.</b></p>

2024-09-09 21:18 UTC, nicolas-sss requested changes

2024-09-09 21:18 UTC, nicolas-sss commented on modules/util/source-formatter/src/test/resources/com/liferay/source/formatter/dependencies/expected/upgrade/UpgradeCatchAllCheck.testjava
> +		String searchEngineId, long companyId, Document documents,
should be document

2024-09-09 21:30 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 37 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e301d27d67447c7a62b04070f891a198a60147fa">e301d27d67447c7a62b04070f891a198a60147fa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MicaelleSilvaa/liferay-portal/tree/LPD-35874">LPD-35874</a><br/>Branch GIT ID: <a href="https://github.com/MicaelleSilvaa/liferay-portal/commit/9ecbba041f49b9d05096c8f2a8b508386c5794f3">9ecbba041f49b9d05096c8f2a8b508386c5794f3</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/4081/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/4081/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] Updated /opt/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/documentation/all_checks.markdown
     [java] Updated /opt/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/documentation/bug_prevention_checks.markdown
     [java] Updated /opt/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/documentation/ci_merge_and_git_repo_source_processor_checks.markdown
     [java] SLF4J: Class path contains multiple SLF4J bindings.
     [java] SLF4J: Found binding in [file:/opt/dev/projects/github/liferay-portal/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
     [java] SLF4J: Actual binding is of type [com.liferay.util.slf4j.LiferayLoggerFactory]
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/util/source-formatter/src/main/resources/documentation/ci_merge_and_git_repo_source_processor_checks.markdown expected:&lt;# Checks for[]
     [java] 
     [java] Check | Category |...&gt; but was:&lt;# Checks for[ ]
     [java] 
     [java] Check | Category |...&gt;
     [java] 2: ./modules/util/source-formatter/README.markdown expected:&lt;...e Extensions:
     [java]    - [[.action, .function, .jelly, .jrxml, .macro, .pom, .project, .properties, .svg, .testcase, .toggle, .tpl, .wsdl, .xml or .xsd](src/main/resources/documentation/xml_source_processor_checks.markdown#checks-for-action-function-jelly-jrxml-macro-pom-project-properties-svg-testcase-toggle-tpl-wsdl-xml-or-xsd)
     [java]    - [.bnd](src/main/resources/documentation/bnd_source_processor_checks.markdown#checks-for-bnd)
     [java]    - [.bnd, .ftl, .gradle, .java, .json, .jsp, .jspf, .scss or .vm](src/main/resources/documentation/upgrade_source_processor_checks.markdown#checks-for-bnd-ftl-gradle-java-json-jsp-jspf-scss-or-vm)
     [java]    - [.bndrun](src/main/resources/documentation/bnd_run_source_processor_checks.markdown#checks-for-bndrun)
     [java]    - [.cfg or .config](src/main/resources/documentation/config_source_processor_checks.markdown#checks-for-cfg-or-config)</pre></details></html>

2024-09-09 21:32 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 35 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e301d27d67447c7a62b04070f891a198a60147fa">e301d27d67447c7a62b04070f891a198a60147fa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MicaelleSilvaa/liferay-portal/tree/LPD-35874">LPD-35874</a><br/>Branch GIT ID: <a href="https://github.com/MicaelleSilvaa/liferay-portal/commit/9ecbba041f49b9d05096c8f2a8b508386c5794f3">9ecbba041f49b9d05096c8f2a8b508386c5794f3</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/4082/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/4082/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] Updated /opt/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/documentation/all_checks.markdown
     [java] Updated /opt/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/documentation/bug_prevention_checks.markdown
     [java] Updated /opt/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/documentation/ci_merge_and_git_repo_source_processor_checks.markdown
     [java] SLF4J: Class path contains multiple SLF4J bindings.
     [java] SLF4J: Found binding in [file:/opt/dev/projects/github/liferay-portal/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
     [java] SLF4J: Actual binding is of type [com.liferay.util.slf4j.LiferayLoggerFactory]
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/util/source-formatter/src/main/resources/documentation/ci_merge_and_git_repo_source_processor_checks.markdown expected:&lt;# Checks for[]
     [java] 
     [java] Check | Category |...&gt; but was:&lt;# Checks for[ ]
     [java] 
     [java] Check | Category |...&gt;
     [java] 2: ./modules/util/source-formatter/README.markdown expected:&lt;...e Extensions:
     [java]    - [[.action, .function, .jelly, .jrxml, .macro, .pom, .project, .properties, .svg, .testcase, .toggle, .tpl, .wsdl, .xml or .xsd](src/main/resources/documentation/xml_source_processor_checks.markdown#checks-for-action-function-jelly-jrxml-macro-pom-project-properties-svg-testcase-toggle-tpl-wsdl-xml-or-xsd)
     [java]    - [.bnd](src/main/resources/documentation/bnd_source_processor_checks.markdown#checks-for-bnd)
     [java]    - [.bnd, .ftl, .gradle, .java, .json, .jsp, .jspf, .scss or .vm](src/main/resources/documentation/upgrade_source_processor_checks.markdown#checks-for-bnd-ftl-gradle-java-json-jsp-jspf-scss-or-vm)
     [java]    - [.bndrun](src/main/resources/documentation/bnd_run_source_processor_checks.markdown#checks-for-bndrun)
     [java]    - [.cfg or .config](src/main/resources/documentation/config_source_processor_checks.markdown#checks-for-cfg-or-config)</pre></details></html>

2024-09-09 21:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/4081/">test-portal-source-format#4081</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/4081/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/208">liferay-devtools#208</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/5836876">[master] ci:test:sf - MicaelleSilvaa &gt; liferay-devtools - PR#208 - 2024-09-09[13:53:46]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>5836876<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/26864/">publish-testray-report#26864</a><br/></div></div>

2024-09-09 21:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/4082/">test-portal-source-format#4082</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/4082/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/208">liferay-devtools#208</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/5836880">[master] ci:test:sf - MicaelleSilvaa &gt; liferay-devtools - PR#208 - 2024-09-09[13:57:46]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>5836880<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/26865/">publish-testray-report#26865</a><br/></div></div>

2024-09-09 21:36 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:hotel - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e301d27d67447c7a62b04070f891a198a60147fa">e301d27d67447c7a62b04070f891a198a60147fa</a></p><details><summary><strong>ci:test:hotel - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10251/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10251/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10251/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>A CI failure has occurred. CI Infrastructure has been notified. Please try again later or contact CI Infrastructure for an update.</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-09-09 21:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10251/">test-portal-acceptance-pullrequest(master)#10251</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10251/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>hotel<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/208">liferay-devtools#208</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/5836884">[master] ci:test:hotel - MicaelleSilvaa &gt; liferay-devtools - PR#208 - 2024-09-09[14:34:32]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>5836884<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/22798/">publish-testray-report#22798</a><br/></div></div>

2024-09-09 21:44 UTC, MicaelleSilvaa commented on modules/util/source-formatter/src/test/resources/com/liferay/source/formatter/dependencies/expected/upgrade/UpgradeCatchAllCheck.testjava
> +		String searchEngineId, long companyId, Document documents,
Resolved :)

2024-09-09 21:46 UTC, MicaelleSilvaa commented
ci:test:sf

2024-09-09 21:46 UTC, MicaelleSilvaa commented
ci:test:hotel

2024-09-09 21:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3834/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3834/jenkins-report.html">here</a>.</b></p>

2024-09-09 22:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>hotel</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6715/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6715/jenkins-report.html">here</a>.</b></p>

2024-09-09 22:15 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 29 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/26deb1222f184b08a1a6dedf9562429238395d86">26deb1222f184b08a1a6dedf9562429238395d86</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MicaelleSilvaa/liferay-portal/tree/LPD-35874">LPD-35874</a><br/>Branch GIT ID: <a href="https://github.com/MicaelleSilvaa/liferay-portal/commit/89ed656641ea0a229245fd0d965c68a68c67a697">89ed656641ea0a229245fd0d965c68a68c67a697</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3834/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3834/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] Updated /opt/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/documentation/all_checks.markdown
     [java] Updated /opt/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/documentation/bug_prevention_checks.markdown
     [java] Updated /opt/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/documentation/ci_merge_and_git_repo_source_processor_checks.markdown
     [java] SLF4J: Class path contains multiple SLF4J bindings.
     [java] SLF4J: Found binding in [file:/opt/dev/projects/github/liferay-portal/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
     [java] SLF4J: Actual binding is of type [com.liferay.util.slf4j.LiferayLoggerFactory]
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/util/source-formatter/src/main/resources/documentation/ci_merge_and_git_repo_source_processor_checks.markdown expected:&lt;# Checks for[]
     [java] 
     [java] Check | Category |...&gt; but was:&lt;# Checks for[ ]
     [java] 
     [java] Check | Category |...&gt;
     [java] 2: ./modules/util/source-formatter/README.markdown expected:&lt;...e Extensions:
     [java]    - [[.action, .function, .jelly, .jrxml, .macro, .pom, .project, .properties, .svg, .testcase, .toggle, .tpl, .wsdl, .xml or .xsd](src/main/resources/documentation/xml_source_processor_checks.markdown#checks-for-action-function-jelly-jrxml-macro-pom-project-properties-svg-testcase-toggle-tpl-wsdl-xml-or-xsd)
     [java]    - [.bnd](src/main/resources/documentation/bnd_source_processor_checks.markdown#checks-for-bnd)
     [java]    - [.bnd, .ftl, .gradle, .java, .json, .jsp, .jspf, .scss or .vm](src/main/resources/documentation/upgrade_source_processor_checks.markdown#checks-for-bnd-ftl-gradle-java-json-jsp-jspf-scss-or-vm)
     [java]    - [.bndrun](src/main/resources/documentation/bnd_run_source_processor_checks.markdown#checks-for-bndrun)
     [java]    - [.cfg or .config](src/main/resources/documentation/config_source_processor_checks.markdown#checks-for-cfg-or-config)</pre></details></html>

2024-09-09 22:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3834/">test-portal-source-format#3834</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3834/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/208">liferay-devtools#208</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/5866764">[master] ci:test:sf - MicaelleSilvaa &gt; liferay-devtools - PR#208 - 2024-09-09[14:47:09]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>5866764<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/14973/">publish-testray-report#14973</a><br/></div></div>

2024-09-09 23:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:hotel - 2 out of 2 jobs passed in 1 hour 16 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/26deb1222f184b08a1a6dedf9562429238395d86">26deb1222f184b08a1a6dedf9562429238395d86</a></p><details><summary><strong>ci:test:hotel - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6715/">test-portal-acceptance-pullrequest(master)</a></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/373579/">modules-unit-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6715/jenkins-report.html">here</a>.</h5></details></html>

2024-09-09 23:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/6715/">test-portal-acceptance-pullrequest(master)#6715</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6715/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>hotel<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/208">liferay-devtools#208</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/5897148">[master] ci:test:hotel - MicaelleSilvaa &gt; liferay-devtools - PR#208 - 2024-09-09[15:12:07]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>5897148<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/14974/">publish-testray-report#14974</a><br/></div></div>

2024-09-10 12:48 UTC, nicolas-sss commented
ci:test:sf

2024-09-10 13:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6543/">test-portal-source-format#6543</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6543/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/208">liferay-devtools#208</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/6564688">[master] ci:test:sf - MicaelleSilvaa &gt; liferay-devtools - PR#208 - 2024-09-10[05:48:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>6564688<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/24123/">publish-testray-report#24123</a><br/></div></div>

2024-09-10 18:25 UTC, MicaelleSilvaa commented
forward to brian: https://github.com/brianchandotcom/liferay-portal/pull/154053

2024-09-10 18:34 UTC, closed without merging