Nicolas - SF Automation - Master - LPD-36648
liferay-devtools/liferay-portal pull request #237
Opened 2024-09-16 21:32 UTC by MicaelleSilvaa

Ticket: https://liferay.atlassian.net/browse/LPD-36648

2024-09-16 21:33 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-09-16 21:33 UTC, MicaelleSilvaa commented
@nicolas-sss

2024-09-16 21:33 UTC, MicaelleSilvaa commented
https://github.com/liferay-devtools/liferay-portal/pull/237

2024-09-16 21:33 UTC, MicaelleSilvaa commented
ci:test:hotel

2024-09-16 21:40 UTC, MicaelleSilvaa commented
ci:test:sf

2024-09-16 21:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/8219/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/8219/jenkins-report.html">here</a>.</b></p>

2024-09-16 22:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 26 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a3b9e6ea8e217048c7b911ca60ce7d4c920611b1">a3b9e6ea8e217048c7b911ca60ce7d4c920611b1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MicaelleSilvaa/liferay-portal/tree/LPD-36648-2">LPD-36648-2</a><br/>Branch GIT ID: <a href="https://github.com/MicaelleSilvaa/liferay-portal/commit/dbf6b14955e9d84b9209ea41d61321ce790fed4e">dbf6b14955e9d84b9209ea41d61321ce790fed4e</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/8219/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/8219/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] SLF4J: Class path contains multiple SLF4J bindings.
     [java] SLF4J: Found binding in [file:/opt/dev/projects/github/liferay-portal/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [java] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
     [java] SLF4J: Actual binding is of type [com.liferay.util.slf4j.LiferayLoggerFactory]
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/util/source-formatter/src/main/resources/dependencies/replacements.json expected:&lt;...ordsDisplayContext"
     [java] [    ],
     [java]     "from": "getSearch",
     [java]     "issueKey": "LPD-36648",
     [java]     "to": "getSearchContainer"
     [java]   ]\},
     [java]   \{
     [java]     "from": "Coo...&gt; but was:&lt;...ordsDisplayContext"
     [java] [        ],
     [java]     "from": "getSearch",
     [java]     "issueKey": "LPD-36648",
     [java]     "to": "getSearchContainer"
     [java]     ]\},
     [java]   \{
     [java]     "from": "Coo...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:473)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:302)
[stopwatch] [run.batch.test.action: 24:43.245 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:448: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-26/job/test-portal-source-format/8219//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240916150828688.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240916150828688.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1316291317.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml</pre></details></html>

2024-09-16 22:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>hotel</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11022/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11022/jenkins-report.html">here</a>.</b></p>

2024-09-16 22:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/8219/">test-portal-source-format#8219</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/8219/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/237">liferay-devtools#237</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/13426409">[master] ci:test:sf - MicaelleSilvaa &gt; liferay-devtools - PR#237 - 2024-09-16[14:42:19]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>13426409<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/32443/">publish-testray-report#32443</a><br/></div></div>

2024-09-17 00:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:hotel - 2 out of 2 jobs passed in 1 hour 44 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a3b9e6ea8e217048c7b911ca60ce7d4c920611b1">a3b9e6ea8e217048c7b911ca60ce7d4c920611b1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9c623c28b91555b7ed3b45e210c832ea4c233bd">d9c623c28b91555b7ed3b45e210c832ea4c233bd</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/12668577">EE Development Acceptance (master) - 830 - 2024-09-14[16:38:16]</a></p><details><summary><strong>ci:test:hotel - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11022/">test-portal-acceptance-pullrequest(master)</a></li><li>modules-unit-jdk8<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/467713/">modules-unit-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11022/jenkins-report.html">here</a>.</h5></details></html>

2024-09-17 00:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11022/">test-portal-acceptance-pullrequest(master)#11022</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11022/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>hotel<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/237">liferay-devtools#237</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/13457811">[master] ci:test:hotel - MicaelleSilvaa &gt; liferay-devtools - PR#237 - 2024-09-16[15:43:25]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>13457811<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/23749/">publish-testray-report#23749</a><br/></div></div>

2024-09-17 12:10 UTC, nicolas-sss commented
ci:test:sf

2024-09-17 12:32 UTC, nicolas-sss requested changes

2024-09-17 12:32 UTC, nicolas-sss commented on modules/util/source-formatter/src/test/resources/com/liferay/source/formatter/dependencies/expected/upgrade/UpgradeCatchAllCheck.testjava
> +	private DDMFormViewFormInstanceRecordsDisplayContext _ddmFormViewFormInstanceRecordsDisplayContext;
@MicaelleSilvaa please create a method receiving this as a parameter. Being a parameter removes the "_" of the variable name.

2024-09-17 19:26 UTC, closed without merging