LPD-30899 Reorder class usages
liferay-devtools/liferay-portal pull request #273
Opened 2024-10-15 01:33 UTC by kyle-miho

2024-10-15 01:33 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-10-15 01:34 UTC, kyle-miho commented
![image](https://github.com/user-attachments/assets/14b45d8c-5e46-4129-84c7-0a85af4c4a0f)
Passed Manual Testing locally following the steps in the Jira Ticket

2024-10-15 14:31 UTC, kyle-miho commented
ci:test:sf

2024-10-15 14:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>hotel</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12782/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12782/jenkins-report.html">here</a>.</b></p>

2024-10-15 14:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/3641/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3641/jenkins-report.html">here</a>.</b></p>

2024-10-15 14:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 27 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9e6ad0e4d897e2d5317231c46841151f8d8a1b32">9e6ad0e4d897e2d5317231c46841151f8d8a1b32</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/kyle-miho/liferay-portal/tree/master-lpd-30899">master-lpd-30899</a><br/>Branch GIT ID: <a href="https://github.com/kyle-miho/liferay-portal/commit/99b4a63f85e02c6f44c67ed876fd7af9677d801a">99b4a63f85e02c6f44c67ed876fd7af9677d801a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3641/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3641/jenkins-report.html">here</a>.</h5></details></html>

2024-10-15 15:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3641/">test-portal-source-format#3641</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3641/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/273">liferay-devtools#273</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/41710625">[master] ci:test:sf - kyle-miho &gt; liferay-devtools - PR#273 - 2024-10-15[07:31:26]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>41710625<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/15001/">publish-testray-report#15001</a><br/></div></div>

2024-10-15 15:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:hotel - 2 out of 2 jobs passed in 48 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9e6ad0e4d897e2d5317231c46841151f8d8a1b32">9e6ad0e4d897e2d5317231c46841151f8d8a1b32</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9e6ad0e4d897e2d5317231c46841151f8d8a1b32">9e6ad0e4d897e2d5317231c46841151f8d8a1b32</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/41675119">EE Development Acceptance (master) - 919 - 2024-10-15[04:38:10]</a></p><details><summary><strong>ci:test:hotel - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12782/">test-portal-acceptance-pullrequest(master)</a></li><li>modules-unit<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1103120/">modules-unit/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12782/jenkins-report.html">here</a>.</h5></details></html>

2024-10-15 15:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12782/">test-portal-acceptance-pullrequest(master)#12782</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12782/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>hotel<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/273">liferay-devtools#273</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/41792725">[master] ci:test:hotel - kyle-miho &gt; liferay-devtools - PR#273 - 2024-10-15[07:31:32]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>41792725<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/27976/">publish-testray-report#27976</a><br/></div></div>

2024-10-15 15:57 UTC, nicolas-sss requested changes

2024-10-15 15:57 UTC, nicolas-sss commented on modules/util/source-formatter/src/main/resources/dependencies/replacements.json
> +		],
@kyle-miho shouldn't be `BigDecimal`?

2024-10-15 19:33 UTC, kyle-miho commented on modules/util/source-formatter/src/main/resources/dependencies/replacements.json
> +		],
@nicolas-sss Oops yea my bad, fixed!

2024-10-17 21:19 UTC, drewbrokke approved these changes

2024-10-18 18:15 UTC, closed without merging