master lpd 42601
liferay-devtools/liferay-portal pull request #313
Opened 2024-12-05 23:42 UTC by kyle-miho

- **LPS-42601 Add parameterized unit tests over from replacements.json**
- **LPD-42601 Only add unique combinations of issueKey and fileType when choosing parameterizedTests**
- **LPD-42601 Remove unneeded new import**

2024-12-06 20:42 UTC, drewbrokke requested changes

2024-12-06 20:42 UTC, drewbrokke commented on modules/util/source-formatter/src/test/java/com/liferay/source/formatter/processor/UpgradeCatchAllCheckTest.java
> +				setMap.entrySet()) {
Check other uses of iterating `map.getEntrySet`. Double-check the variable names for the `stringSetEntry` variable and the `setMap` variable here, whether or not they should be "generic" names (e.g. `map`, `entry`) or "purpose-built" names (e.g. `issueKeyFileTypesMap`,  `issueKeyFileTypesEntry`) or some combination of the two.

In any case, I think we should change the current variable names.

2024-12-06 21:36 UTC, kyle-miho commented
ci:test:sf

2024-12-06 21:37 UTC, kyle-miho commented
ci:test:hotel

2024-12-06 21:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>hotel</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19064/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19064/jenkins-report.html">here</a>.</b></p>

2024-12-06 21:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/6461/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6461/jenkins-report.html">here</a>.</b></p>

2024-12-06 22:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 28 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c21da3ceadf0abb80f3a284d05771a40671999b">8c21da3ceadf0abb80f3a284d05771a40671999b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/kyle-miho/liferay-portal/tree/master-lpd-42601">master-lpd-42601</a><br/>Branch GIT ID: <a href="https://github.com/kyle-miho/liferay-portal/commit/ca41d18e7cb265bc39bef5fc478a95e45e08887e">ca41d18e7cb265bc39bef5fc478a95e45e08887e</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/6461/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6461/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./workspaces/liferay-learn-workspace/client-extensions/liferay-learn-batch/batch/02-object-definition.batch-engine-data.json expected:&lt;...nswers"
     [java]           \},
     [java]         [  ]"name": "p2s3QuizQue...&gt; but was:&lt;...nswers"
     [java]           \},
     [java]         []"name": "p2s3QuizQue...&gt;
     [java] 2: ./modules/sdk/gradle-plugins-jasper-jspc/src/main/java/com/liferay/gradle/plugins/jasper/jspc/CompileJSPTask.java expected:&lt;...paceAware, validate,[
     [java]           ]blockExternal) \{
     [java] 
     [java]     ...&gt; but was:&lt;...paceAware, validate,[ ]blockExternal) \{
     [java] 
     [java]     ...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:472)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 26:20.535 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:448: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null734351823.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null914459596
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 144ms
[junitreport] Deleting: /tmp/null914459596
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-06-2024 14:04:55:963 PST
[stopwatch] [run.batch.test.tear.down: 0.001 sec]
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null734351823.properties</pre></details></html>

2024-12-06 22:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/6461/">test-portal-source-format#6461</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/6461/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/313">liferay-devtools#313</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/86105782">[master] ci:test:sf - kyle-miho &gt; liferay-devtools - PR#313 - 2024-12-06[13:36:47]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>86105782<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/25121/">publish-testray-report#25121</a><br/></div></div>

2024-12-06 22:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:hotel - 2 out of 2 jobs passed in 42 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c21da3ceadf0abb80f3a284d05771a40671999b">8c21da3ceadf0abb80f3a284d05771a40671999b</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c21da3ceadf0abb80f3a284d05771a40671999b">8c21da3ceadf0abb80f3a284d05771a40671999b</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/85939682">EE Development Acceptance (master) - 1064 - 2024-12-06[08:37:50]</a></p><details><summary><strong>ci:test:hotel - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19064/">test-portal-acceptance-pullrequest(master)</a></li><li>modules-unit<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1041713/">modules-unit/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19064/jenkins-report.html">here</a>.</h5></details></html>

2024-12-06 22:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19064/">test-portal-acceptance-pullrequest(master)#19064</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19064/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>hotel<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-devtools/liferay-portal/pull/313">liferay-devtools#313</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/86143353">[master] ci:test:hotel - kyle-miho &gt; liferay-devtools - PR#313 - 2024-12-06[13:37:21]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>86143353<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/41228/">publish-testray-report#41228</a><br/></div></div>

2024-12-06 22:25 UTC, drewbrokke approved these changes

2024-12-06 22:28 UTC, drewbrokke commented
Looks good, thanks @kyle-miho!

2024-12-09 16:40 UTC, kyle-miho commented
https://github.com/brianchandotcom/liferay-portal/pull/156792

2024-12-09 16:40 UTC, closed without merging